name: dressme-app

services:
  # 1. Base de Datos Local con pgvector
  dressme-db:
    image: ankane/pgvector:latest
    container_name: dressme-db
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: dressmedb
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: password123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-pgvector.sql:/docker-entrypoint-initdb.d/init-pgvector.sql
    networks:
      - dressme-network

  # 2. Microservicio de Base de Datos
  dressme-database:
    build: 
      context: ./dressme-database/dressme-database
      dockerfile: Dockerfile # <-- Apunta explícitamente al local
    container_name: dressme-database
    ports:
      - "8082:8080"
    depends_on:
      - dressme-db
    networks:
      - dressme-network

  # 3. Microservicio Cerebro / Orquestador
  dressme-back:
    build: 
      context: ./dressme-back/dressme-back
      dockerfile: Dockerfile # <-- Apunta explícitamente al local
    container_name: dressme-back
    ports:
      - "8081:8080"
    depends_on:
      - dressme-database
    networks:
      - dressme-network

  # 4. Microservicio Gateway (Público)
  dressme-gateway:
    build: 
      context: ./dressme-gateway/dressme-gateway
      dockerfile: Dockerfile # <-- Apunta explícitamente al local
    container_name: dressme-gateway
    ports:
      - "8080:8080"
    depends_on:
      - dressme-back
    networks:
      - dressme-network

networks:
  dressme-network:
    driver: bridge

volumes:
  postgres_data: