# Dockerfile.prod (Para uso en PRODUCCIÓN / Nube)

# ETAPA 1: Construcción (Build)
FROM maven:3.9.6-eclipse-temurin-21-alpine AS build
WORKDIR /app

# 1. Copiamos solo el pom.xml primero para aprovechar el caché de Docker
COPY pom.xml .
# 2. Descargamos las dependencias (si el pom no cambia, Docker no repite esto)
RUN mvn dependency:go-offline

# 3. Copiamos el código fuente
COPY src ./src
# 4. Compilamos el proyecto e ignoramos los tests para un despliegue más rápido
RUN mvn clean package -DskipTests

# ETAPA 2: Ejecución (Run)
FROM eclipse-temurin:21-jdk-alpine
VOLUME /tmp

# Copiamos el .jar generado en la Etapa 1 hacia esta imagen final limpia
COPY --from=build /app/target/*.jar app.jar

EXPOSE 8080
ENTRYPOINT ["java","-jar","/app.jar"]